In [1]:
import numpy as np

In [2]:
# 1 задание

v = np.array([9,8,7,6,5,4,3,2,1,0])

In [19]:
v

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
# 2 задание

# 1-й пример

M = np.array([[9,7,4],[4,10,6],[10,8,-12]])

In [13]:
M

array([[  9,   7,   4],
       [  4,  10,   6],
       [ 10,   8, -12]])

In [14]:
print('Diagonal (sum): ', np.trace(M))
print('Diagonal (elements): ', np.diagonal(M))

Diagonal (sum):  7
Diagonal (elements):  [  9  10 -12]


In [15]:
# 2-й пример

M = np.diag([4,7,-2])

In [16]:
M

array([[ 4,  0,  0],
       [ 0,  7,  0],
       [ 0,  0, -2]])

In [17]:
print('Diagonal (sum): ', np.trace(M))
print('Diagonal (elements): ', np.diagonal(M))

Diagonal (sum):  9
Diagonal (elements):  [ 4  7 -2]


In [34]:
# 3 задание

from numpy import linalg

M = np.array([[4,2,1], [1,3,0], [0,5,4]])
v = np.array([4,12,-3])

In [35]:
M

array([[4, 2, 1],
       [1, 3, 0],
       [0, 5, 4]])

In [36]:
v

array([ 4, 12, -3])

In [37]:
np.linalg.solve(M, v)

array([ 0.46666667,  3.84444444, -5.55555556])

In [38]:
# 4 задание

# 1-й пример

a = np.random.rand(3)
b = np.random.rand(3)

In [43]:
a

array([0.87079461, 0.06504077, 0.86111846])

In [42]:
b

array([0.97029358, 0.07037256, 0.40832706])

In [44]:
np.dot(a,b)

1.2011214735486846

In [45]:
# 2-й пример

a = np.random.rand(3)
b = np.random.rand(3)

In [46]:
a

array([0.5260903 , 0.54087886, 0.52996778])

In [47]:
b

array([0.89536945, 0.33212973, 0.99995741])

In [48]:
np.dot(a,b)

1.1806323361811217